version: "3.8"

services:
  appsmith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appsmith
    environment:
      - SERVICE_FQDN_APPSMITH
      - 'APPSMITH_MAIL_ENABLED=${APPSMITH_MAIL_ENABLED:-false}'
      - 'APPSMITH_MAIL_FROM=${APPSMITH_MAIL_FROM:-admin@example.com}'
      - 'APPSMITH_REPLY_TO=${APPSMITH_REPLY_TO:-reply@example.com}'
      - 'APPSMITH_MAIL_HOST=${APPSMITH_MAIL_HOST:-smtp.example.com}'
      - 'APPSMITH_MAIL_PORT=${APPSMITH_MAIL_PORT:-587}'
      - 'APPSMITH_MAIL_SMTP_TLS_ENABLED=${APPSMITH_MAIL_SMTP_TLS_ENABLED:-true}'
      - 'APPSMITH_MAIL_USERNAME=${APPSMITH_MAIL_USERNAME}'
      - 'APPSMITH_MAIL_PASSWORD=${APPSMITH_MAIL_PASSWORD}'
      - 'APPSMITH_DISABLE_TELEMETRY=${APPSMITH_DISABLE_TELEMETRY:-false}'
      - 'APPSMITH_DISABLE_INTERCOM=${APPSMITH_DISABLE_INTERCOM:-true}'
      - 'APPSMITH_SENTRY_DSN=${APPSMITH_SENTRY_DSN}'
      - 'APPSMITH_SMART_LOOK_ID=${APPSMITH_SMART_LOOK_ID}'
      - 'APPSMITH_HIDE_APP_BRANDING=${APPSMITH_HIDE_APP_BRANDING:-true}'
    depends_on:
      - mongo
      - redis
    volumes:
      - ./stacks:/appsmith-stacks

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
